openapi: 3.0.3
info:
  description: Calendar API for AppSheet.
  version: 0.0.1
  title: AppSheet Calendar
servers:
  - url: 'https://34.107.178.221.nip.io'
security:
  - ApiKeyAuth: []

paths:
  /events:
    get:
      tags:
        - event
      summary: List 'Calendar Events' objects.
      description: List specific events from Google Calendar API with flat format (no nested fields)
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                      $ref: '#/components/schemas/ListOfEvents'

    post:
      tags:
        - event
      summary: Insert an event 
      requestBody:
        description: Event to be created
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        '200':
          description: OK
        '400':
          description: Invalid asset supplied

  /events/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: The event id
    get:
      tags:
        - event
      summary: Get an event by id
      responses:
        '200':
          description: event retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '404':
          description: Event not found
    put:
      tags:
        - event
      summary: Update an event by id
      requestBody:
        description: event to be created
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        '200':
          description: Event retrieved
        '400':
          description: Invalid event supplied
        '404':
          description: Event not found 
    delete:
      tags:
        - event
      summary: Delete the event by id
      responses:
        '200':
          description: OK
        '404':
          description: Event not found



components:
  schemas:
    Event:
      title: Event
      type: object
      properties:
        id:
          description: The _id of the Event
          type: string
          example: 0fml87qma068pjam62qvith0pj
        status:
          description: The status of the Event
          type: string
          example: confirmed
        htmlLink:
          description: The htmlLink of the Event
          type: string
          example: https://www.google.com/calendar/event?eid=MGZtbDg3cW1hMDY4cGphbTYycXZpdGgwcGogYXBpbG92ZXJAbGVicnVuLnNwYWNl
        organizer:
          description: The email of the Event organizer
          type: string
          example: apilover@lebrun.space
        eventType:
          description: The eventType of the Event
          type: string
          example: default
        startDateTime:
          description: The startDateTime of the Event
          type: string
          example: 2023-04-05T11:15:00+02:00
        endDateTime:
          description: The endDateTime of the Event
          type: string
          example: 2023-04-05T13:00:00+02:00
        NotesFileURL:
          description: The NotesFileURL of the Event
          type: string
          example: https://docs.google.com/document/d/1ya6aBJgHXpkxH-gjFvVpM1AS6QIryjZMmT9_DTagRB8/edit
        NotesFileId:
          description: The eventType of the Event
          type: string
          example: 1ya6aBJgHXpkxH-gjFvVpM1AS6QIryjZMmT9_DTagRB8
    ListOfEvents:
      type: object
      properties:
        asset:
          type: array
          items:
            $ref: '#/components/schemas/Event'

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-apikey
