swagger: '2.0'
info:
  title: AppSheet Calendar
  version: "1"
  description: Demo Products API for Hipster Application
basePath: https://34.107.178.221.nip.io
securityDefinitions:
  ApiKeyAuth:
    type: "apiKey"
    in: "header"
    name: "x-apikey"
security:
  - ApiKeyAuth: []
paths:
  /products:
    get:
      responses:
        '200':
          description: A successful response.
      tags:
        - ProductCatalogService

