openapi: "3.0.0"
info:
  title: AppSheet Calendar
  version: "1"
  description: Demo Products API for Hipster Application
servers:
  - url: https://34.107.178.221.nip.io
paths:
  /products:
    get:
      operationId: GetProducts
      responses:
        '200':
          description: A successful response.
          schema:
            $ref: '#/definitions/hipstershopListProductsResponse'
      tags:
        - ProductCatalogService
     x-filter:
       type: RHS-Colon
       
security:
  - ApiKeyAuth: []
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-APIKey
    
