openapi: 3.0.2
info:
  title: AppSheet Calendar
  version: "1"
  description: Demo Products API for Hipster Application
servers:
  - url: 'https://34.107.178.221.nip.io'
security:
  - ApiKeyAuth: []

paths:
  /products:
    get:
      tags:
        - products
      summary: List all Products
      responses:
        '200':
          description: Products list retrieved.


components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-apikey
    

